name: cloudy_app
description: Weather app use flutter
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  easy_localization: ^1.3.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_platform_widgets: ^1.20.0
  flutter_svg: ^1.0.3
  geolocator: ^5.2.1
  intl: ^0.17.0
  table_calendar: ^3.0.5

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/cloudysun.png
    - assets/images/image1.png
    - assets/images/image2.png
    - assets/images/image3.png
    - assets/images/image4.png
    - assets/images/image5.png
    - assets/images/image6.png
    - assets/images/mapweather.png
    - assets/images/mapsweather.png
    - assets/images/news.png
    - assets/images/cloud.png
    - assets/images/wind.svg
    - assets/images/rain.svg
    - assets/images/sun.svg
    - assets/images/location.svg
    - assets/images/jammenu.svg
    - assets/images/search.svg
    - assets/images/drawermenu.svg
    - assets/images/locationmenu.svg
    - assets/images/sunmark.svg
    - assets/images/back.svg
    - assets/images/setting.svg
    - assets/images/share.svg
    - assets/images/promo.svg
    - assets/images/arrowleft.svg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
